/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/lil_bear.glb -o src/components/Character.jsx -r public 
Author: mikequeen123 (https://sketchfab.com/mikequeen123)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lil-bear-55ee397cf40c4f86af1ee31fb2096d82
Title: Lil Bear
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Character(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/lil_bear.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
    >
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, -1.1]}
          scale={0.13}
        >
          <group
            name="83df5fd26fab49e096c869191560ab1cfbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="metarig"
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_42"
                      rotation={[-Math.PI / 2, 0, 0]}
                    />
                    <group
                      name="Object_45"
                      rotation={[-Math.PI / 2, 0, 0]}
                    />
                    <skinnedMesh
                      name="Object_43"
                      geometry={nodes.Object_43.geometry}
                      material={materials.Body}
                      skeleton={nodes.Object_43.skeleton}
                      morphTargetDictionary={
                        nodes.Object_43.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Object_43.morphTargetInfluences
                      }
                    />
                    <skinnedMesh
                      name="Object_44"
                      geometry={nodes.Object_44.geometry}
                      material={materials.MouthShapes}
                      skeleton={nodes.Object_44.skeleton}
                      morphTargetDictionary={
                        nodes.Object_44.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Object_44.morphTargetInfluences
                      }
                    />
                    <skinnedMesh
                      name="Object_46"
                      geometry={nodes.Object_46.geometry}
                      material={materials.Coat}
                      skeleton={nodes.Object_46.skeleton}
                    />
                  </group>
                </group>
                <group
                  name="Body"
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <group
                  name="Coat"
                  rotation={[-Math.PI / 2, 0, 0]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/lil_bear.glb");
